services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: atlas
      POSTGRES_DB: atlas
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
