version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - atlas-config:/app/config
    networks:
      - atlas
    environment:
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas_password
    networks:
      - atlas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlas -d atlas"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  atlas:

volumes:
  atlas-config:
    name: atlas-config
  postgres_data:
